controller_manager:
  ros__parameters:
    update_rate: 100

    big_arm_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

big_arm_joint_trajectory_controller:
  ros__parameters:
    allow_nonzero_velocity_at_trajectory_end: false
    joints:
      - big_arm_joint_2
      - big_arm_joint_3
      - big_arm_joint_4
      - big_arm_joint_5
      - big_arm_joint_6
      - big_arm_joint_7
      - big_arm_joint_8                              
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
