#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from builtin_interfaces.msg import Duration

from std_msgs.msg import String, Float64
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from std_srvs.srv import Empty

class MoveArm(Node):

    def __init__(self):
        super().__init__('arm_node')
        self.arm_publisher_ = self.create_publisher(JointTrajectory, '/little_arm/joint_trajectory_controller/joint_trajectory', 10)
        self.open_srv = self.create_service(Empty, 'open_arm', self.open_arm_callback)
        self.close_srv = self.create_service(Empty, 'close_arm', self.close_arm_callback)
        self.random_srv = self.create_service(Empty, 'random_arm', self.random_arm_callback)


    def open_arm_callback(self, request, response):
        traj = JointTrajectory()
        traj.joint_names = ["little_arm_joint_2", "little_arm_joint_3", "little_arm_joint_4", "little_arm_joint_5", "little_arm_joint_6", "little_arm_joint_7", "little_arm_joint_8", "little_arm_joint_9"]
        
        point1 = JointTrajectoryPoint()
        point1.positions = [-1.2, -0.4, -1.0, 1.5, 0.4, 0.0, 0.0, 0.0]
        point1.time_from_start = Duration(sec=10)

        traj.points.append(point1)
        self.arm_publisher_.publish(traj)


        return response

    def close_arm_callback(self, request, response):
        traj = JointTrajectory()
        traj.joint_names = ["little_arm_joint_2", "little_arm_joint_3", "little_arm_joint_4", "little_arm_joint_5", "little_arm_joint_6", "little_arm_joint_7", "little_arm_joint_8", "little_arm_joint_9"]
        
        point1 = JointTrajectoryPoint()
        point1.positions = [-0.8, 0.0, -0.8, 0.15, -0.6, 0.0, 0.0, 0.0]
        point1.time_from_start = Duration(sec=10)

        traj.points.append(point1)
        self.arm_publisher_.publish(traj)

        return response

    def random_arm_callback(self, request, response):
        traj = JointTrajectory()
        traj.joint_names = ["little_arm_joint_2", "little_arm_joint_3", "little_arm_joint_4", "little_arm_joint_5", "little_arm_joint_6", "little_arm_joint_7", "little_arm_joint_8", "little_arm_joint_9", 0.0]
        
        point1 = JointTrajectoryPoint()
        point1.positions = [-1.95, 0.0, -2.0, 0.085, -0.75, 0.28, 0.0]
        point1.time_from_start = Duration(sec=4)

        traj.points.append(point1)
        self.arm_publisher_.publish(traj)

        return response


def main(args=None):
    rclpy.init(args=args)

    arm_node = MoveArm()

    rclpy.spin(arm_node)
    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    arm_node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
